services:
  main-db:
    image: postgres:16.1
    container_name: postgres2
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=main_svc
      - POSTGRES_USER=main_svc
      - POSTGRES_DB=main_svc
      - TZ=Europe/Moscow
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
  stat-svc:
    build: stat_svc
    image: explore-with-me-stat_svc
    container_name: explore-with-me-stat_svc
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stat_svc
      - SPRING_DATASOURCE_USERNAME=stat_svc
      - SPRING_DATASOURCE_PASSWORD=stat_svc
      - TZ=Europe/Moscow
    depends_on:
      - stats-db

  stats-db:
    image: postgres:16.1
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=stat_svc
      - POSTGRES_USER=stat_svc
      - POSTGRES_DB=stat_svc
      - TZ=Europe/Moscow
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  main-svc:
    build: main_svc
    image: explore-with-me-main_svc
    container_name: explore-with-me-main_svc
    ports:
      - "8080:8080"
    environment:
      - EXPLORE_WITH_ME_STAT_SVC_URL=http://stat-svc:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-db:5432/main_svc
      - SPRING_DATASOURCE_USERNAME=main_svc
      - SPRING_DATASOURCE_PASSWORD=main_svc
      - TZ=Europe/Moscow
    depends_on:
      - main-db


