version: '3.8'
services:
  stats-server:
    build: ./stat_svc
    image: stats-server-image
    container_name: stats-server-container
    ports:
      - "9090:9090"
    depends_on:
      stats-db:
        condition: service_healthy
    environment:
      - SPRING_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/exploreWM
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  stats-db:
    image: postgres:16.1
    container_name: stats-db-container
    ports:
      - 6541:5432
    environment:
      - POSTGRES_DB=exploreWM
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d exploreWM"]
      interval: 5s
      timeout: 5s
      retries: 10

  ewm-service:
    build: ./main_svc
    image: main-service-image
    container_name: main-service-container
    ports:
      - "8080:8080"
    depends_on:
      ewm-db:
        condition: service_healthy
      stats-server:
        condition: service_started
    environment:
      - STATS_SERVER_URL=http://stats-server:9090
      - SPRING_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/exploreMAIN
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  ewm-db:
    image: postgres:16.1
    container_name: ewm-db-container
    ports:
      - 6542:5432
    environment:
      - POSTGRES_DB=exploreMAIN
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d exploreMAIN"]
      interval: 5s
      timeout: 5s
      retries: 10